-- File: practice/indexes/02-create-and-measure.sql
-- Objective: Create indexes that improve the queries from 01-explain-baseline.sql, and prove it.
--
-- TODO:
--   For each query, decide what index would help, CREATE it, then re-run EXPLAIN ANALYZE.
--   Confirm the plan changed AND the time dropped.
--
--   Q3.  Expression index — CREATE INDEX ... ON users (LOWER(email));
--   Q4.  Trigram or GIN — requires `CREATE EXTENSION IF NOT EXISTS pg_trgm;`
--          then  CREATE INDEX ... ON songs USING GIN (title gin_trgm_ops);
--   Q5.  Already covered by idx_playlist_songs_song from the schema — verify.
--
--   Also try:
--   - Index for top-N: CREATE INDEX ... ON songs(play_count DESC);
--   - Composite: CREATE INDEX ... ON play_history(user_id, played_at DESC);
--
-- TODO journal:
--   - Compare timings before/after for each query.
--   - Which indexes hurt write throughput most? (Try INSERT 1000 songs in a loop and time it.)

-- Your code here:
