-- File: practice/indexes/04-find-unused.sql
-- Objective: Audit which indexes are actually used; drop the dead ones.
--
-- TODO:
--   Run a diverse workload first (the queries from 01-explain-baseline.sql, multiple times).
--
--   1. List every index and its scan count:
--        SELECT schemaname, relname AS table, indexrelname AS index, idx_scan
--        FROM pg_stat_user_indexes
--        ORDER BY idx_scan ASC, relname;
--
--   2. List indexes that have NEVER been scanned (idx_scan = 0) — candidates for removal.
--
--   3. Find duplicate / overlapping indexes:
--        SELECT indrelid::regclass AS table,
--               array_agg(indexrelid::regclass) AS overlapping
--        FROM pg_index
--        GROUP BY indrelid, indkey
--        HAVING COUNT(*) > 1;
--
-- TODO action:
--   - Drop one index you've decided is unused. Re-run your benchmark queries to confirm
--     nothing regressed. If something did regress, recreate the index — measurements > guesses.

-- Your code here:
