-- File: practice/procedures/01-add-song-to-playlist.sql
-- Objective: Stored procedure that adds a song to a playlist atomically.
--
-- TODO:
--   Create PROCEDURE add_song_to_playlist(p_playlist_id INT, p_song_id INT)
--     1. Compute next position = MAX(position)+1 for the playlist.
--     2. INSERT INTO playlist_songs (playlist_id, song_id, position).
--     3. UPDATE playlists SET song_count = song_count + 1, modified_at = NOW()
--        WHERE playlist_id = p_playlist_id.
--   Handle:
--     - unique_violation (song already in playlist) → RAISE NOTICE and return without error.
--     - foreign_key_violation → RAISE EXCEPTION 'invalid playlist or song'.
--
-- TODO test:
--   CALL add_song_to_playlist(1, 50);
--   CALL add_song_to_playlist(1, 50);
--   SELECT song_count FROM playlists WHERE playlist_id = 1;

-- Your code here:
