-- File: practice/procedures/02-create-playlist.sql
-- Objective: Procedure that creates a playlist and adds an initial set of songs in one transaction.
--
-- TODO:
--   Create PROCEDURE create_playlist_with_songs(
--       p_user_id INT,
--       p_name    VARCHAR,
--       p_song_ids INT[]
--   )
--     1. INSERT a new playlist (RETURNING playlist_id into a variable).
--     2. UNNEST p_song_ids WITH ORDINALITY and bulk-insert into playlist_songs.
--     3. UPDATE playlists.song_count to array_length(p_song_ids, 1).
--   The whole thing must roll back if ANY song_id is invalid.
--
-- TODO test:
--   CALL create_playlist_with_songs(1, 'New Mix', ARRAY[1,2,3,4]);
--   CALL create_playlist_with_songs(1, 'Bad Mix', ARRAY[1,2,9999999]);

-- Your code here:
