-- File: practice/procedures/03-calculate-stats.sql
-- Objective: Function that returns aggregate statistics for a user.
--
-- TODO:
--   Create FUNCTION user_stats(p_user_id INT)
--   RETURNS TABLE(
--       total_plays      BIGINT,
--       total_seconds    BIGINT,
--       favorite_genre   VARCHAR,
--       playlists_owned  INT,
--       last_played_at   TIMESTAMP
--   )
--   that joins users → play_history → songs → albums → artists.
--
--   - favorite_genre = artist genre with the highest play count for this user.
--   - last_played_at = MAX(played_at) from play_history for this user.
--
-- TODO test:
--   SELECT * FROM user_stats(1);

-- Your code here:
