-- File: practice/procedures/04-cleanup-empty-playlists.sql
-- Objective: Maintenance procedure that deletes empty playlists older than N days.
--
-- TODO:
--   Create PROCEDURE cleanup_empty_playlists(p_days INT, OUT p_deleted INT)
--     1. DELETE FROM playlists
--        WHERE song_count = 0
--          AND created_at < NOW() - make_interval(days => p_days);
--     2. GET DIAGNOSTICS p_deleted = ROW_COUNT;
--     3. Log the cleanup to audit_log (one summary row).
--
-- TODO test:
--   CALL cleanup_empty_playlists(30, NULL);

-- Your code here:
