-- File: practice/cursors/01-simple-cursor.sql
-- Objective: Iterate over a result set with an explicit cursor.
--
-- TODO:
--   Inside a DO $$ ... $$ block:
--     1. DECLARE a CURSOR FOR SELECT song_id, title, duration_seconds
--                              FROM songs WHERE play_count > 1000000
--                              ORDER BY play_count DESC.
--     2. OPEN it.
--     3. LOOP / FETCH / EXIT WHEN NOT FOUND.
--     4. RAISE NOTICE one line per row.
--     5. CLOSE.

-- Your code here:
