-- File: practice/cursors/03-cursor-in-procedure.sql
-- Objective: Combine a cursor with a stored procedure for batch maintenance.
--
-- TODO:
--   Create PROCEDURE expire_inactive_users(p_months INT)
--     - Iterate (with a cursor) over users whose latest play_history is older than p_months
--       OR who have no play_history at all.
--     - For each such user:
--         UPDATE users SET subscription = 'free' WHERE user_id = rec.user_id;
--         UPDATE user_sessions SET is_active = FALSE WHERE user_id = rec.user_id;
--         INSERT a row into audit_log describing the expiration.
--   Use proper exception handling so a single failing user doesn't kill the whole run
--   (hint: BEGIN / EXCEPTION inside the loop, or SAVEPOINT per row).
--
-- TODO test:
--   CALL expire_inactive_users(12);

-- Your code here:
