-- File: practice/cursors/04-nested-cursors.sql
-- Objective: Practice nested cursors (artist → albums → songs).
--
-- TODO:
--   Inside a DO $$ ... $$ block:
--     - Outer cursor: SELECT artist_id, name FROM artists ORDER BY name.
--     - Middle cursor (parameterized): SELECT album_id, title FROM albums WHERE artist_id = $1.
--     - Inner cursor (parameterized): SELECT title, duration_seconds FROM songs WHERE album_id = $1.
--     - Print a tree:
--         Artist Foo
--           Album Bar (2021)
--             - Track 1 (213s)
--             - Track 2 (180s)
--
-- TODO compare:
--   Achieve the same output with a single SELECT + ORDER BY using string concatenation or
--   GROUP BY + array_agg. Notice how unmaintainable the cursor version is by comparison.

-- Your code here:
